### ISSUE TITLE
既然自己懒得搞那就只好认真摸索别人的了-被一些人诟病的mybatis二级缓存

### ISSUE THREAD

**Issue by zazaluMonster** [zazaluMonster/zazaluMonster.github.io#21]
https://zazalu.space/2019/07/31/mybatis-level-2-cache-global-i/ 

 1 简单介绍mybatis是javaweb开发再熟悉不过的orm框架。没有公司内部自研的orm框架的话，我见过的基本现在都走mybatis或者spring-jpa 为了加速查询，减少数据库I/O次数，我们都需要缓存这玩意来辅助我们存储一些数据在内存中，利用内存查询速度很快的特点，来让我们的读操作耗时更短。 2 吐槽PerpetualCache我最近经常听人吐槽mybatis的缓存机制（无中生有？）

**Comment by nanshouyong** [comment]
老师，我在myper下启用 cache 但执行同一个方案没有缓存，每次都打印sql出来，请指导下啊。

**Comment by zazaluMonster** [comment]
> @nanshouyong
> 老师，我在myper下启用 cache 但执行同一个方案没有缓存，每次都打印sql出来，请指导下啊。

0. 是否是mybatis3+版本
1. 检查是否配置了cacheEnabled=false
2. 如果1不满足,检查你执行的mybatis-statement是否配置useCache=false或者flushCache=true
3. 如果都不满足, 你可以发你的配置文件截图上来, 或者自己仔细查阅[mybatis3官方文档](https://mybatis.org/mybatis-3/zh/index.html)
